version: "3"

networks:
  incredible-squaring-network:
    name: incredible-squaring-network
    driver: bridge

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    ports:
      - 8545:8545
    entrypoint: anvil
    volumes:
      - ./docker-compose/anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    networks:
      - incredible-squaring-network

  aggregator:
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    container_name: incredible-squaring-aggregator
    ports:
      - 8080:8080
    depends_on:
      anvil:
        condition: service_started
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: 
      - --config 
      - config-files/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
      - --shared-avs-contracts-deployment 
      - contracts/script/output/31337/shared_avs_contracts_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
    networks:
      - incredible-squaring-network

  machine1:
    image: zippiehq/cartesi-lambada:1.1
    container_name: incredible-squaring-machine1
    volumes:
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator1:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator1
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine1:5001
      - LAMBADA_ADDRESS=machine1:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=abGY2KUk2STIAJHxa3jo
      - OPERATOR_ECDSA_KEY_PASSWORD=iPa6lQcv0boT1W0ZWejT
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator1.yaml
    networks:
      - incredible-squaring-network

  machine2:
    image: zippiehq/cartesi-lambada:1.1
    container_name: incredible-squaring-machine2
    volumes:
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator2:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator2
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine2:5001
      - LAMBADA_ADDRESS=machine2:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=qoFsf3Ahs78oXFiEXAOe
      - OPERATOR_ECDSA_KEY_PASSWORD=tVMhkzNujOF2cBxJF4Qv
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator2.yaml
    networks:
      - incredible-squaring-network

  machine3:
    image: zippiehq/cartesi-lambada:1.1
    container_name: incredible-squaring-machine3
    volumes:
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator3:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator3
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine3:5001
      - LAMBADA_ADDRESS=machine3:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=eYr9EbMKp0YoAhQmkh6H
      - OPERATOR_ECDSA_KEY_PASSWORD=ncRDJ1u1KZ5CS5fcQRrq
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator3.yaml
    networks:
      - incredible-squaring-network
