version: "3"

networks:
  incredible-squaring-network:
    name: incredible-squaring-network
    driver: bridge

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    ports:
      - 8545:8545
    entrypoint: anvil
    volumes:
      - ./docker-compose/anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    networks:
      - incredible-squaring-network

  aggregator:
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    container_name: incredible-squaring-aggregator
    ports:
      - 8080:8080
    depends_on:
      anvil:
        condition: service_started
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: 
      - --config 
      - config-files/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
      - --shared-avs-contracts-deployment 
      - contracts/script/output/31337/shared_avs_contracts_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
    networks:
      - incredible-squaring-network

  machine1:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine1
    volumes:
      - ./docker-compose/operators/data/operator1:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator1:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator1
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine1:5001
      - LAMBADA_ADDRESS=machine1:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=oZ05pFMys8hZCQzQaXIe
      - OPERATOR_ECDSA_KEY_PASSWORD=59pSGYqsKBgh5LWSnuKF
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator1.yaml
    networks:
      - incredible-squaring-network

  machine2:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine2
    volumes:
      - ./docker-compose/operators/data/operator2:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator2:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator2
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine2:5001
      - LAMBADA_ADDRESS=machine2:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=QrMHt4kQzwRneWagaESN
      - OPERATOR_ECDSA_KEY_PASSWORD=eYhqiDzoDg5V1BT4ea0I
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator2.yaml
    networks:
      - incredible-squaring-network

  machine3:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine3
    volumes:
      - ./docker-compose/operators/data/operator3:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator3:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator3
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine3:5001
      - LAMBADA_ADDRESS=machine3:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=ys5m9n5dyRjAgJVBrguq
      - OPERATOR_ECDSA_KEY_PASSWORD=g7RHIF3xJxGzAQEhUQLM
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator3.yaml
    networks:
      - incredible-squaring-network

  machine4:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine4
    volumes:
      - ./docker-compose/operators/data/operator4:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator4:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator4
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine4:5001
      - LAMBADA_ADDRESS=machine4:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=qDSPtDE7dOJzFBK1T24t
      - OPERATOR_ECDSA_KEY_PASSWORD=yIGEaSTPSmjJhP9NJJrW
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator4.yaml
    networks:
      - incredible-squaring-network

  machine5:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine5
    volumes:
      - ./docker-compose/operators/data/operator5:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator5:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator5
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine5:5001
      - LAMBADA_ADDRESS=machine5:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=0sPtdrNK9Oksh7nOugZn
      - OPERATOR_ECDSA_KEY_PASSWORD=rkvVlRq6eJCetpmSmKAd
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator5.yaml
    networks:
      - incredible-squaring-network

  machine6:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine6
    volumes:
      - ./docker-compose/operators/data/operator6:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator6:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator6
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine6:5001
      - LAMBADA_ADDRESS=machine6:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=9d4RczoHZyeFaB6oix5G
      - OPERATOR_ECDSA_KEY_PASSWORD=iMSMAldXHgRTerEAB5uu
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator6.yaml
    networks:
      - incredible-squaring-network

  machine7:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine7
    volumes:
      - ./docker-compose/operators/data/operator7:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator7:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator7
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine7:5001
      - LAMBADA_ADDRESS=machine7:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=3BeKU3aXooNajwUqIyyF
      - OPERATOR_ECDSA_KEY_PASSWORD=hTyr470bX0BcU0OekoyN
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator7.yaml
    networks:
      - incredible-squaring-network

  machine8:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine8
    volumes:
      - ./docker-compose/operators/data/operator8:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator8:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator8
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine8:5001
      - LAMBADA_ADDRESS=machine8:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=6ePePq21M4U9Z6ohI83J
      - OPERATOR_ECDSA_KEY_PASSWORD=YapDcF59m6ihcmsx8aZZ
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator8.yaml
    networks:
      - incredible-squaring-network

  machine9:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine9
    volumes:
      - ./docker-compose/operators/data/operator9:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator9:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator9
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine9:5001
      - LAMBADA_ADDRESS=machine9:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=r6bcJr8YxYUILI2iDsmb
      - OPERATOR_ECDSA_KEY_PASSWORD=OTeQLxmyYOuoXxYChDJs
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator9.yaml
    networks:
      - incredible-squaring-network

  machine10:
    image: zippiehq/cartesi-lambada:1.5
    container_name: incredible-squaring-machine10
    volumes:
      - ./docker-compose/operators/data/operator10:/data
      - ./machine:/data/preload
    networks:
      - incredible-squaring-network
    environment:
      - COMPUTE_ONLY=1

  operator10:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: incredible-squaring-operator10
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine10:5001
      - LAMBADA_ADDRESS=machine10:3033
      - LAMBADA_COMPUTE_CID=bafybeif5liyov4oltxvc34qh3uyyxy5znisbmarsorxrp4nr3o7ywjuo5u
      - OPERATOR_BLS_KEY_PASSWORD=fvEXmZWyDCpp1ckQ27GX
      - OPERATOR_ECDSA_KEY_PASSWORD=TCJxCth8uCODpWbBq7Im
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config docker-compose/operators/configs/operator10.yaml
    networks:
      - incredible-squaring-network
